### ISSUE TITLE
Show something useful when failing to ssh into a project/environment

### ISSUE THREAD

**Issue by klonos** [amazeeio/lagoon-cli#75]
```
lagoon ssh -p education-sa -e master
panic: Failed to dial: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
goroutine 1 [running]:
github.com/amazeeio/lagoon-cli/lagoon/ssh.InteractiveSSH(0xc000141b80, 0x0, 0x0, 0x0, 0x0, 0xc000141bb0)
	/go/src/github.com/amazeeio/lagoon-cli/lagoon/ssh/main.go:17 +0x90a
github.com/amazeeio/lagoon-cli/cmd.glob..func48(0x1a6b280, 0xc0000def80, 0x0, 0x4)
	/go/src/github.com/amazeeio/lagoon-cli/cmd/ssh.go:58 +0x76b
github.com/spf13/cobra.(*Command).execute(0x1a6b280, 0xc0000deec0, 0x4, 0x4, 0x1a6b280, 0xc0000deec0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x1a6ab00, 0x0, 0x0, 0x14d0b23)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/amazeeio/lagoon-cli/cmd.Execute()
	/go/src/github.com/amazeeio/lagoon-cli/cmd/root.go:61 +0x42
main.main()
	/go/src/github.com/amazeeio/lagoon-cli/main.go:8 +0x20
```

It was that the project name was incorrect after all, but the above errors lead me to believe that there was something wrong with the authentication. It could be somethings like "no such project" or "no such environment" (suggestions of close matches would be a plus 🙂😉)

**Comment by shreddedbacon** [comment]
Thanks @klonos will look into this. Agree the panic is a bit excessive 😆

**Comment by klonos** [comment]
Yup, as per discussions over Slack, something like `Check that the project or environment you are trying to connect to exists` might be best.
